replicaCount: 2
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: aks.tietoevry.site
      paths:
        - "/*"
  tls:
    - secretName: aks-tietoevry-tls
      hosts:
        - aks.tietoevry.site
